version: '3.8'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./logs/nginx:/var/log/nginx
    depends_on:
      - web
    restart: always
    networks:
      - scraper_network

  web:
    build: .
    environment:
      - FLASK_ENV=production
    restart: always
    expose:
      - 5000
    networks:
      - scraper_network

networks:
  scraper_network:
    driver: bridge
